### ISSUE TITLE
"Invalid URL: https"

### ISSUE THREAD

**Issue by Pentaphon** [TachibanaGeneralLaboratories/download-navi#16] opened 2019-04-26 09:31 UTC
When I paste an https URL in the link box and press connect, it turns red and says "invalid URL; https"

![ubuntu](https://user-images.githubusercontent.com/49374058/56798354-6c080e00-67cb-11e9-942c-f91faeec8b75.jpg)

**Comment by proninyaroslav** [comment] 2019-04-26 09:37
Will be fixed soon.

**Closed by proninyaroslav** 2019-04-26 09:37 UTC

**Comment by smaragdus** [comment] 2019-04-26 17:21
The same problem here:

**screen:**

![Download Navi - 2019-04-26 - error - 002](https://user-images.githubusercontent.com/9025757/56824955-9657db00-6860-11e9-84e6-24cae5121e0f.png)

The URL is absolutely valid.

#15 is really fixed but in version [1.0.2](https://github.com/TachibanaGeneralLaboratories/download-navi/releases/tag/1.0.2) `Connect` does not work.

**Comment by proninyaroslav** [comment] 2019-04-26 17:36
Fix will be included in 1.0.3

**Comment by smaragdus** [comment] 2019-04-26 17:38
@proninyaroslav 

> Fix will be included in 1.0.3

Thanks.

**Comment by smaragdus** [comment] 2019-04-28 03:28
@proninyaroslav 

I tested version [1.0.3](https://github.com/TachibanaGeneralLaboratories/download-navi/releases/tag/1.0.3), the problem is really fixed, thanks. By the way `Auto connect` option is handy. If it happens that I encounter other problems I will report them.
