### ISSUE TITLE
[Bug] Download not resuming if less free space than entire file

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#143] opened 2021-02-14 19:36 UTC
Hello,

Let's say you have 1 GB of free space.

Try starting a 0.75 GB file download : it works.

At 0.5 GB downloaded, pause it.

You have now 0.5 GB of space left, which is more than the remaining 0.25 GB to download.

But, try resuming download : it fails.

My guess is : the app is expecting 1 GB of free space like if it was starting from the beginning.

Thanks

**Comment by proninyaroslav** [comment] 2021-04-27 09:53
Try to disable pre-allocate disk space in the Settings -> Storage.

**Comment by KaKi87** [comment] 2021-04-27 11:40
I'll try, but will this be fixed?

**Comment by proninyaroslav** [comment] 2021-04-27 14:04
In this case, this is not a bug, because you are trying to allocate space in advance, and if there is not enough disk space, then you will fail.

**Comment by KaKi87** [comment] 2021-04-27 14:07
> Try starting a 0.75 GB file download : it works.

At this point, space allocation succeeded.

> At 0.5 GB downloaded, pause it.

At this point, space allocation is preserved.

> But, try resuming download : it fails.

At this point, space allocation should have been preserved.

**Comment by proninyaroslav** [comment] 2021-04-27 14:29
Probably the problem is with this place. It checks the free space, but since the file size is already allocated, there is no free space, it just doesn't know that the space is already reserved. I need to think about how to implement it differently. 

https://github.com/TachibanaGeneralLaboratories/download-navi/blob/45eec8ed3aab7e02c21c9dd997e04166d4e5f566/app/src/main/java/com/tachibana/downloader/core/model/DownloadThreadImpl.java#L401-L406

**Comment by proninyaroslav** [comment] 2021-04-27 16:00
Fixed by https://github.com/TachibanaGeneralLaboratories/download-navi/commit/37379b5171ccd6c8fe8efc8ecca22d094d381665#diff-af5e49b2a79158a87cc304475c2710bfbc55a155464dd671b94dde07f20637a2

**Closed** 2021-04-27 15:59 UTC
Labels: bug

**Comment by KaKi87** [comment] 2021-04-27 17:20
Nice, thanks!
